export const details_response = [
  {
    id: 4965,
    cris_id: 4965,
    title:
      "Supporting Creative Group Processes – Groupware for Communication and Coordination",
    subtitle: null,
    title_in_source:
      "Supporting Creative Group Processes – Groupware for Communication and Coordination",
    language: "English",
    external: "Internal",
    content_type: null,
    peer_reviewed: "Ja",
    volume: null,
    venue: "Lima, Peru",
    graduation_type: null,
    graduation_year: null,
    institution: null,
    publication_status: "Published",
    abstract: null,
    keywords: null,
    affiliation: null,
    journal_name: null,
    journal_abbreviation: null,
    issn: null,
    publication_year: "2010",
    publication_date: null,
    publication_type: "Aufsatz (Konferenz)",
    publication_type_key: "570",
    edition: null,
    journal_volume: null,
    journal_issue: null,
    start_page: "1",
    end_page: "10",
    pages_range: null,
    book_title: null,
    book_subtitle: null,
    number_of_pages: null,
    editor: null,
    conference:
      "Proceedings of the 16th Americas Conference on Information Systems (AMCIS2010)",
    title_of_series: null,
    place: null,
    publisher: null,
    isbn: null,
    doi: null,
    url: "http://www.wi.uni-muenster.de/is/",
    authors: "Becker Jörg, Bergener Katrin, Voigt Matthias",
    strings: null,
    sort_order: "1010-Becker-Jörg",
    client_purpose: null,
    publication_id: 2791,
    card_id: 6115,
    person_id: 6608,
    orga_unit_id: 4965,
    orga_unit_lsf_number: "37406",
    orga_unit_name:
      "[[[entry:1]]]Lehrstuhl für Wirtschaftsinformatik und Informationsmanagement[[[/entry]]][[[entry:2]]]Chair for Information Systems and Information Management[[[/entry]]]",
    orga_unit_acronym: "IS",
    person_salutation: "Herr",
    person_first_name: "Jörg",
    person_last_name: "Becker",
    person_academic_title: "Prof. Dr. Dr. h.c.",
    person_additional_title: null,
    person_status: "Professor(in)",
    person_status_key: "1619",
    person_ziv_account: "beckerj",
    person_permalink: "joerg-becker",
    function: "Wissenschaftliches Personal",
    function_key: "1477",
    start_date: "1990-04-01",
    end_date: "2024-02-29",
    email: "info@wi.uni-muenster.de",
    phone: "+49 251 83-38100",
    fax: "+49 251 83-38109",
    room: "133",
    consultation_hours: null,
    group_in_organisation: "Professor",
    outdated: 0,
    permalink: "joerg-becker",
    parent_id: 4959,
    lsf_number: "37406",
    name: "[[[entry:1]]]Lehrstuhl für Wirtschaftsinformatik und Informationsmanagement[[[/entry]]][[[entry:2]]]Chair for Information Systems and Information Management[[[/entry]]]",
    acronym: "IS",
    description:
      '[[[entry:1]]]<img style="padding-right: 10px; width: 50%;" src="https://www.wi.uni-muenster.de/sites/wi/files/public/department/is/lehrstuhlbecker.jpg" alt="" align="left" />\r\n<p>Der Lehrstuhl f&uuml;r Wirtschaftsinformatik und \t\t\t\tInformationsmanagement unter der Leitung von Prof. Dr. Dr. h.c. J&ouml;rg Becker hat sich dem Forschen und Lehren von Inhalten der Informationssysteme und des Informationsmanagements verschrieben. 28 Wissenschaftliche Mitarbeiter und 20 Studentische Hilfskr&auml;fte arbeiten zur Zeit am Lehrstuhl in Bereichen der Lehre und der Forschung.</p>\r\n<p>Der Forschungsschwerpunkt des Lehrstuhls ist die Prozess- und Datenmodellierung. Neben der Entwicklung und Evaluation neuer Methoden steht der Ergebnistransfer in die Praxis, insbesondere in den Dom&auml;nen Dienstleistung, E-Government und Handel im Vordergrund. Durch eine Einbindung in das European Research Center for Information Systems (<a href="https://www.ercis.org">ERCIS</a>) wird dabei gezielt ein interdisziplin&auml;rer L&ouml;sungsansatz verfolgt, der Kernkompetenzen der Wirtschaftsinformatik, Informatik, Betriebswirtschaft und Rechtswissenschaft integriert.</p>\r\n<p>Die Aktivit&auml;ten des Lehrstuhls werden im j&auml;hrlich erscheinenden Jahresbericht ver&ouml;ffentlicht. <a href="https://www.wi.uni-muenster.de/sites/wi/files/seitenstruktur/das-institut/gruppen/is/lehrstuhljahresbericht_2019.pdf">Download</a></p>\r\n<p>Im Rahmen der Bachelor- und Masterstudieng&auml;nge werden insbesondere Lehrveranstaltungen zu den Kernthemen Prozessmodellierung (Anwendungssysteme, Information Modelling, Workflow Management and Petri Nets) und Datenmodellierung (Datenmanagement, Management Information Systems and Data Warehousing) angeboten. Begleitend wird den Studierenden schon fr&uuml;h im Studium dom&auml;nenspezifisches Wissen im Rahmen von Vertiefungsmodulen, Projektseminaren und Seminaren vermittelt. Dabei werden auch Soft Skills wie Pr&auml;sentationstechniken und Rhetorik erarbeitet und geschult. Alle Lehrveranstaltungen zeichnen sich durch einen ausgepr&auml;gten Bezug zu aktuellen Transferprojekten und Forschungsprojekten aus.</p>[[[/entry]]][[[entry:2]]]<img style="padding-right: 10px; width: 50%;" src="https://www.wi.uni-muenster.de/sites/wi/files/public/department/is/lehrstuhlbecker.jpg" alt="" align="left" />The Chair for Information Systems and Information Management at the University of Muenster is directed by Prof. Dr. Dr. h.c. Joerg Becker. Focus areas of research are Process Modeling and Data Modeling. Besides developing and evaluating new modeling methods, the methods are transferred into practice to generate business value for companies and governmental organizations. Focused domains of research comprise Service Science Management and Engineering (SSME), E-Government and Retail/Wholesale. As the chair is embedded into the European Research Center for Information Systems (<a href="https://www.ercis.org">ERCIS</a>), the research projects incorporate Information Systems, Computer Science, Business Administration, and Legal points of view.[[[/entry]]]',
    street: "Leonardo-Campus 3",
    postal_code: "48149",
    city: "Münster",
    country: "Germany",
    admin_number: "37406",
    short_name:
      "[[[entry:1]]]WI + Informationsmanagement[[[/entry]]][[[entry:2]]]Information Systems and Information Management[[[/entry]]]",
    name_searchable:
      "Lehrstuhl für Wirtschaftsinformatik und Informationsmanagement",
    external_profile: "",
    number: "37406",
    prof_person_id: 6608,
    prof_salutation: "Herr",
    prof_first_name: "Jörg",
    prof_last_name: "Becker",
    prof_academic_title: "Prof. Dr. Dr. h.c.",
    prof_additional_title: null,
    prof_status: "Professor(in)",
    prof_status_key: "1619",
    prof_ziv_account: "beckerj",
  },
  {
    id: 4965,
    cris_id: 4965,
    title:
      "Supporting Creative Group Processes – Groupware for Communication and Coordination",
    subtitle: null,
    title_in_source:
      "Supporting Creative Group Processes – Groupware for Communication and Coordination",
    language: "English",
    external: "Internal",
    content_type: null,
    peer_reviewed: "Ja",
    volume: null,
    venue: "Lima, Peru",
    graduation_type: null,
    graduation_year: null,
    institution: null,
    publication_status: "Published",
    abstract: null,
    keywords: null,
    affiliation: null,
    journal_name: null,
    journal_abbreviation: null,
    issn: null,
    publication_year: "2010",
    publication_date: null,
    publication_type: "Aufsatz (Konferenz)",
    publication_type_key: "570",
    edition: null,
    journal_volume: null,
    journal_issue: null,
    start_page: "1",
    end_page: "10",
    pages_range: null,
    book_title: null,
    book_subtitle: null,
    number_of_pages: null,
    editor: null,
    conference:
      "Proceedings of the 16th Americas Conference on Information Systems (AMCIS2010)",
    title_of_series: null,
    place: null,
    publisher: null,
    isbn: null,
    doi: null,
    url: "http://www.wi.uni-muenster.de/is/",
    authors: "Becker Jörg, Bergener Katrin, Voigt Matthias",
    strings: null,
    sort_order: "1130-Bergener-Katrin",
    client_purpose: null,
    publication_id: 2791,
    card_id: 8309,
    person_id: 8990,
    orga_unit_id: 4965,
    orga_unit_lsf_number: "37406",
    orga_unit_name:
      "[[[entry:1]]]Lehrstuhl für Wirtschaftsinformatik und Informationsmanagement[[[/entry]]][[[entry:2]]]Chair for Information Systems and Information Management[[[/entry]]]",
    orga_unit_acronym: "IS",
    person_salutation: "Frau",
    person_first_name: "Katrin",
    person_last_name: "Bergener",
    person_academic_title: "Dr.",
    person_additional_title: null,
    person_status: "Wissenschaftlicher Assistent",
    person_status_key: "1741",
    person_ziv_account: "kfiel_01",
    person_permalink: "katrin-bergener",
    function: "Wissenschaftliches Personal",
    function_key: "1477",
    start_date: "2006-07-03",
    end_date: "2010-09-30",
    email: "info@wi.uni-muenster.de",
    phone: "+49 251 83-38100",
    fax: "+49 251 83-38109",
    room: "032",
    consultation_hours: null,
    group_in_organisation: "PostDoc",
    outdated: 0,
    permalink: "katrin-bergener",
    parent_id: 4959,
    lsf_number: "37406",
    name: "[[[entry:1]]]Lehrstuhl für Wirtschaftsinformatik und Informationsmanagement[[[/entry]]][[[entry:2]]]Chair for Information Systems and Information Management[[[/entry]]]",
    acronym: "IS",
    description:
      '[[[entry:1]]]<img style="padding-right: 10px; width: 50%;" src="https://www.wi.uni-muenster.de/sites/wi/files/public/department/is/lehrstuhlbecker.jpg" alt="" align="left" />\r\n<p>Der Lehrstuhl f&uuml;r Wirtschaftsinformatik und \t\t\t\tInformationsmanagement unter der Leitung von Prof. Dr. Dr. h.c. J&ouml;rg Becker hat sich dem Forschen und Lehren von Inhalten der Informationssysteme und des Informationsmanagements verschrieben. 28 Wissenschaftliche Mitarbeiter und 20 Studentische Hilfskr&auml;fte arbeiten zur Zeit am Lehrstuhl in Bereichen der Lehre und der Forschung.</p>\r\n<p>Der Forschungsschwerpunkt des Lehrstuhls ist die Prozess- und Datenmodellierung. Neben der Entwicklung und Evaluation neuer Methoden steht der Ergebnistransfer in die Praxis, insbesondere in den Dom&auml;nen Dienstleistung, E-Government und Handel im Vordergrund. Durch eine Einbindung in das European Research Center for Information Systems (<a href="https://www.ercis.org">ERCIS</a>) wird dabei gezielt ein interdisziplin&auml;rer L&ouml;sungsansatz verfolgt, der Kernkompetenzen der Wirtschaftsinformatik, Informatik, Betriebswirtschaft und Rechtswissenschaft integriert.</p>\r\n<p>Die Aktivit&auml;ten des Lehrstuhls werden im j&auml;hrlich erscheinenden Jahresbericht ver&ouml;ffentlicht. <a href="https://www.wi.uni-muenster.de/sites/wi/files/seitenstruktur/das-institut/gruppen/is/lehrstuhljahresbericht_2019.pdf">Download</a></p>\r\n<p>Im Rahmen der Bachelor- und Masterstudieng&auml;nge werden insbesondere Lehrveranstaltungen zu den Kernthemen Prozessmodellierung (Anwendungssysteme, Information Modelling, Workflow Management and Petri Nets) und Datenmodellierung (Datenmanagement, Management Information Systems and Data Warehousing) angeboten. Begleitend wird den Studierenden schon fr&uuml;h im Studium dom&auml;nenspezifisches Wissen im Rahmen von Vertiefungsmodulen, Projektseminaren und Seminaren vermittelt. Dabei werden auch Soft Skills wie Pr&auml;sentationstechniken und Rhetorik erarbeitet und geschult. Alle Lehrveranstaltungen zeichnen sich durch einen ausgepr&auml;gten Bezug zu aktuellen Transferprojekten und Forschungsprojekten aus.</p>[[[/entry]]][[[entry:2]]]<img style="padding-right: 10px; width: 50%;" src="https://www.wi.uni-muenster.de/sites/wi/files/public/department/is/lehrstuhlbecker.jpg" alt="" align="left" />The Chair for Information Systems and Information Management at the University of Muenster is directed by Prof. Dr. Dr. h.c. Joerg Becker. Focus areas of research are Process Modeling and Data Modeling. Besides developing and evaluating new modeling methods, the methods are transferred into practice to generate business value for companies and governmental organizations. Focused domains of research comprise Service Science Management and Engineering (SSME), E-Government and Retail/Wholesale. As the chair is embedded into the European Research Center for Information Systems (<a href="https://www.ercis.org">ERCIS</a>), the research projects incorporate Information Systems, Computer Science, Business Administration, and Legal points of view.[[[/entry]]]',
    street: "Leonardo-Campus 3",
    postal_code: "48149",
    city: "Münster",
    country: "Germany",
    admin_number: "37406",
    short_name:
      "[[[entry:1]]]WI + Informationsmanagement[[[/entry]]][[[entry:2]]]Information Systems and Information Management[[[/entry]]]",
    name_searchable:
      "Lehrstuhl für Wirtschaftsinformatik und Informationsmanagement",
    external_profile: "",
    number: "37406",
    prof_person_id: 6608,
    prof_salutation: "Herr",
    prof_first_name: "Jörg",
    prof_last_name: "Becker",
    prof_academic_title: "Prof. Dr. Dr. h.c.",
    prof_additional_title: null,
    prof_status: "Professor(in)",
    prof_status_key: "1619",
    prof_ziv_account: "beckerj",
  },
  {
    id: 4965,
    cris_id: 4965,
    title:
      "Supporting Creative Group Processes – Groupware for Communication and Coordination",
    subtitle: null,
    title_in_source:
      "Supporting Creative Group Processes – Groupware for Communication and Coordination",
    language: "English",
    external: "Internal",
    content_type: null,
    peer_reviewed: "Ja",
    volume: null,
    venue: "Lima, Peru",
    graduation_type: null,
    graduation_year: null,
    institution: null,
    publication_status: "Published",
    abstract: null,
    keywords: null,
    affiliation: null,
    journal_name: null,
    journal_abbreviation: null,
    issn: null,
    publication_year: "2010",
    publication_date: null,
    publication_type: "Aufsatz (Konferenz)",
    publication_type_key: "570",
    edition: null,
    journal_volume: null,
    journal_issue: null,
    start_page: "1",
    end_page: "10",
    pages_range: null,
    book_title: null,
    book_subtitle: null,
    number_of_pages: null,
    editor: null,
    conference:
      "Proceedings of the 16th Americas Conference on Information Systems (AMCIS2010)",
    title_of_series: null,
    place: null,
    publisher: null,
    isbn: null,
    doi: null,
    url: "http://www.wi.uni-muenster.de/is/",
    authors: "Becker Jörg, Bergener Katrin, Voigt Matthias",
    strings: null,
    sort_order: "1280-Voigt-Matthias",
    client_purpose: null,
    publication_id: 2791,
    card_id: 9338,
    person_id: 10103,
    orga_unit_id: 4965,
    orga_unit_lsf_number: "37406",
    orga_unit_name:
      "[[[entry:1]]]Lehrstuhl für Wirtschaftsinformatik und Informationsmanagement[[[/entry]]][[[entry:2]]]Chair for Information Systems and Information Management[[[/entry]]]",
    orga_unit_acronym: "IS",
    person_salutation: "Herr",
    person_first_name: "Matthias",
    person_last_name: "Voigt",
    person_academic_title: "Dr.",
    person_additional_title: null,
    person_status: "Wissenschaftlicher Mitarbeiter",
    person_status_key: "1730",
    person_ziv_account: "mvoig_01",
    person_permalink: "matthias-voigt",
    function: "Wissenschaftliches Personal",
    function_key: "1477",
    start_date: "2008-10-01",
    end_date: "2010-09-30",
    email: "info@wi.uni-muenster.de",
    phone: "+49 251 83-38100",
    fax: "+49 251 83-38109",
    room: null,
    consultation_hours: null,
    group_in_organisation: "Ehemalige Mitarbeiter",
    outdated: 0,
    permalink: "matthias-voigt",
    parent_id: 4959,
    lsf_number: "37406",
    name: "[[[entry:1]]]Lehrstuhl für Wirtschaftsinformatik und Informationsmanagement[[[/entry]]][[[entry:2]]]Chair for Information Systems and Information Management[[[/entry]]]",
    acronym: "IS",
    description:
      '[[[entry:1]]]<img style="padding-right: 10px; width: 50%;" src="https://www.wi.uni-muenster.de/sites/wi/files/public/department/is/lehrstuhlbecker.jpg" alt="" align="left" />\r\n<p>Der Lehrstuhl f&uuml;r Wirtschaftsinformatik und \t\t\t\tInformationsmanagement unter der Leitung von Prof. Dr. Dr. h.c. J&ouml;rg Becker hat sich dem Forschen und Lehren von Inhalten der Informationssysteme und des Informationsmanagements verschrieben. 28 Wissenschaftliche Mitarbeiter und 20 Studentische Hilfskr&auml;fte arbeiten zur Zeit am Lehrstuhl in Bereichen der Lehre und der Forschung.</p>\r\n<p>Der Forschungsschwerpunkt des Lehrstuhls ist die Prozess- und Datenmodellierung. Neben der Entwicklung und Evaluation neuer Methoden steht der Ergebnistransfer in die Praxis, insbesondere in den Dom&auml;nen Dienstleistung, E-Government und Handel im Vordergrund. Durch eine Einbindung in das European Research Center for Information Systems (<a href="https://www.ercis.org">ERCIS</a>) wird dabei gezielt ein interdisziplin&auml;rer L&ouml;sungsansatz verfolgt, der Kernkompetenzen der Wirtschaftsinformatik, Informatik, Betriebswirtschaft und Rechtswissenschaft integriert.</p>\r\n<p>Die Aktivit&auml;ten des Lehrstuhls werden im j&auml;hrlich erscheinenden Jahresbericht ver&ouml;ffentlicht. <a href="https://www.wi.uni-muenster.de/sites/wi/files/seitenstruktur/das-institut/gruppen/is/lehrstuhljahresbericht_2019.pdf">Download</a></p>\r\n<p>Im Rahmen der Bachelor- und Masterstudieng&auml;nge werden insbesondere Lehrveranstaltungen zu den Kernthemen Prozessmodellierung (Anwendungssysteme, Information Modelling, Workflow Management and Petri Nets) und Datenmodellierung (Datenmanagement, Management Information Systems and Data Warehousing) angeboten. Begleitend wird den Studierenden schon fr&uuml;h im Studium dom&auml;nenspezifisches Wissen im Rahmen von Vertiefungsmodulen, Projektseminaren und Seminaren vermittelt. Dabei werden auch Soft Skills wie Pr&auml;sentationstechniken und Rhetorik erarbeitet und geschult. Alle Lehrveranstaltungen zeichnen sich durch einen ausgepr&auml;gten Bezug zu aktuellen Transferprojekten und Forschungsprojekten aus.</p>[[[/entry]]][[[entry:2]]]<img style="padding-right: 10px; width: 50%;" src="https://www.wi.uni-muenster.de/sites/wi/files/public/department/is/lehrstuhlbecker.jpg" alt="" align="left" />The Chair for Information Systems and Information Management at the University of Muenster is directed by Prof. Dr. Dr. h.c. Joerg Becker. Focus areas of research are Process Modeling and Data Modeling. Besides developing and evaluating new modeling methods, the methods are transferred into practice to generate business value for companies and governmental organizations. Focused domains of research comprise Service Science Management and Engineering (SSME), E-Government and Retail/Wholesale. As the chair is embedded into the European Research Center for Information Systems (<a href="https://www.ercis.org">ERCIS</a>), the research projects incorporate Information Systems, Computer Science, Business Administration, and Legal points of view.[[[/entry]]]',
    street: "Leonardo-Campus 3",
    postal_code: "48149",
    city: "Münster",
    country: "Germany",
    admin_number: "37406",
    short_name:
      "[[[entry:1]]]WI + Informationsmanagement[[[/entry]]][[[entry:2]]]Information Systems and Information Management[[[/entry]]]",
    name_searchable:
      "Lehrstuhl für Wirtschaftsinformatik und Informationsmanagement",
    external_profile: "",
    number: "37406",
    prof_person_id: 6608,
    prof_salutation: "Herr",
    prof_first_name: "Jörg",
    prof_last_name: "Becker",
    prof_academic_title: "Prof. Dr. Dr. h.c.",
    prof_additional_title: null,
    prof_status: "Professor(in)",
    prof_status_key: "1619",
    prof_ziv_account: "beckerj",
  },
];
